name: go_router_samples
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.6
  gap: ^3.0.1
  go_router: ^12.1.1
  lottie: ^2.6.0
  riverpod_annotation: ^2.3.1
  swipeable_button_view: ^0.0.2
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.7
  go_router_builder: ^2.3.4

flutter:
  uses-material-design: true
  assets:
    - images/
    - lottie/