enum Product {
  bunny(
    id: '001',
    name: 'bunny dash',
    category: ProductCategory.image,
    description: 'hop! hop!',
    tag: 'bunny',
    price: 100000,
    imagePath: 'images/bunny_dash.png',
  ),
  coffee(
    id: '002',
    name: 'coffee dash',
    category: ProductCategory.image,
    description: 'coffee! coffee!',
    tag: 'coffee',
    price: 100000,
    imagePath: 'images/coffee_dash.png',
  ),
  fire(
    id: '003',
    name: 'fire dash',
    category: ProductCategory.image,
    description: 'fire! fire!',
    tag: 'fire',
    price: 100000,
    imagePath: 'images/fire_dash.png',
  ),
  guiter(
    id: '004',
    name: 'guiter dash',
    category: ProductCategory.image,
    description: 'guiter! guiter!',
    tag: 'guiter',
    price: 100000,
    imagePath: 'images/guiter_dash.png',
  ),
  gym(
    id: '005',
    name: 'gym dash',
    category: ProductCategory.image,
    description: 'gym! gym!',
    tag: 'gym',
    price: 100000,
    imagePath: 'images/gym_dash.png',
  ),
  pencil(
    id: '006',
    name: 'pencil dash',
    category: ProductCategory.image,
    description: 'pencil! pencil!',
    tag: 'pencil',
    price: 100000,
    imagePath: 'images/pencil_dash.png',
  ),
  professor(
    id: '007',
    name: 'professor dash',
    category: ProductCategory.image,
    description: 'professor! professor!',
    tag: 'professor',
    price: 100000,
    imagePath: 'images/professor_dash.png',
  ),
  superman(
    id: '008',
    name: 'superman dash',
    category: ProductCategory.image,
    description: 'superman! superman!',
    tag: 'superman',
    price: 100000,
    imagePath: 'images/superman_dash.png',
  ),
  artist(
    id: '009',
    name: 'artist dash',
    category: ProductCategory.image,
    description: 'artist! artist!',
    tag: 'artist',
    price: 100000,
    imagePath: 'images/artist_dash.png',
  ),
  sleep(
    id: '010',
    name: 'sleep dash',
    category: ProductCategory.image,
    description: 'sleep! sleep!',
    tag: 'sleep',
    price: 100000,
    imagePath: 'images/sleep_dash.png',
  ),
  skateboard(
    id: '011',
    name: 'skateboard dash',
    category: ProductCategory.image,
    description: 'skateboard! skateboard!',
    tag: 'skateboard',
    price: 100000,
    imagePath: 'images/skateboard_dash.png',
  ),
  donut(
    id: '012',
    name: 'donut dash',
    category: ProductCategory.image,
    description: 'donut! donut!',
    tag: 'donut',
    price: 100000,
    imagePath: 'images/donut_dash.png',
  ),
  stickerDash(
    id: '013',
    name: 'sticker dash',
    category: ProductCategory.sticker,
    description: 'sticker! sticker!',
    tag: 'st_dash',
    price: 100000,
    imagePath: 'images/dash_sticker01.png',
  ),
  stickerDartSide(
    id: '014',
    name: 'sticker dart side',
    category: ProductCategory.sticker,
    description: 'sticker! sticker!',
    tag: 'st_dart_side',
    price: 100000,
    imagePath: 'images/dash_sticker02.png',
  ),
  stickerSinging(
    id: '015',
    name: 'sticker singing',
    category: ProductCategory.sticker,
    description: 'sticker! sticker!',
    tag: 'st_singing',
    price: 100000,
    imagePath: 'images/dash_sticker03.png',
  ),
  stickerShouting(
    id: '016',
    name: 'sticker shouting',
    category: ProductCategory.sticker,
    description: 'sticker! sticker!',
    tag: 'st_shouting',
    price: 100000,
    imagePath: 'images/dash_sticker04.png',
  ),
  stickerGlasses(
    id: '017',
    name: 'sticker glasses',
    category: ProductCategory.sticker,
    description: 'sticker! sticker!',
    tag: 'st_glasses',
    price: 100000,
    imagePath: 'images/dash_sticker05.png',
  ),
  stickerTeaching(
    id: '018',
    name: 'sticker teaching',
    category: ProductCategory.sticker,
    description: 'sticker! sticker!',
    tag: 'st_teaching',
    price: 100000,
    imagePath: 'images/dash_sticker06.png',
  ),
  stickerLove(
    id: '019',
    name: 'sticker love',
    category: ProductCategory.sticker,
    description: 'sticker! sticker!',
    tag: 'st_love',
    price: 100000,
    imagePath: 'images/dash_sticker07.png',
  ),
  tshirtDash(
    id: '020',
    name: 'tshirt dash',
    category: ProductCategory.tshirt,
    description: 'tshirt! tshirt!',
    tag: 'ts_dash',
    price: 100000,
    imagePath: 'images/tshirt_dash.png',
  ),
  tshirtGlasses(
    id: '021',
    name: 'tshirt glasses',
    category: ProductCategory.tshirt,
    description: 'tshirt! tshirt!',
    tag: 'ts_glasses',
    price: 100000,
    imagePath: 'images/tshirt_glasses.png',
  ),
  tshirtHi(
    id: '022',
    name: 'tshirt hi',
    category: ProductCategory.tshirt,
    description: 'tshirt! tshirt!',
    tag: 'ts_hi',
    price: 100000,
    imagePath: 'images/tshirt_hi.png',
  ),
  tshirtCombi(
    id: '023',
    name: 'tshirt combi',
    category: ProductCategory.tshirt,
    description: 'tshirt! tshirt!',
    tag: 'ts_combi',
    price: 100000,
    imagePath: 'images/tshirt_combi.png',
  ),
  tshirtDarth(
    id: '024',
    name: 'tshirt darth',
    category: ProductCategory.tshirt,
    description: 'tshirt! tshirt!',
    tag: 'ts_darth',
    price: 100000,
    imagePath: 'images/tshirt_darth.png',
  ),
  tshirtRocket(
    id: '025',
    name: 'tshirt rocket',
    category: ProductCategory.tshirt,
    description: 'tshirt! tshirt!',
    tag: 'ts_rocket',
    price: 100000,
    imagePath: 'images/tshirt_rocket.png',
  ),
  tshirtSing(
    id: '026',
    name: 'tshirt sing',
    category: ProductCategory.tshirt,
    description: 'tshirt! tshirt!',
    tag: 'ts_sing',
    price: 100000,
    imagePath: 'images/tshirt_sing.png',
  ),
  tshirtShouting(
    id: '027',
    name: 'tshirt shouting',
    category: ProductCategory.tshirt,
    description: 'tshirt! tshirt!',
    tag: 'ts_shouting',
    price: 100000,
    imagePath: 'images/tshirt_shouting.png',
  ),
  stuffedDash2(
    id: '029',
    name: 'stuffed dash2',
    category: ProductCategory.stuffed,
    description: 'stuffed! stuffed!',
    tag: 'stu_dash2',
    price: 100000,
    imagePath: 'images/stuffed_dash2.png',
  ),
  stuffedBig(
    id: '030',
    name: 'stuffed big',
    category: ProductCategory.stuffed,
    description: 'stuffed! stuffed!',
    tag: 'stu_big',
    price: 100000,
    imagePath: 'images/stuffed_big.png',
  ),
  stuffedGlasses(
    id: '031',
    name: 'stuffed glasses',
    category: ProductCategory.stuffed,
    description: 'stuffed! stuffed!',
    tag: 'stu_glasses',
    price: 100000,
    imagePath: 'images/stuffed_glasses.png',
  ),
  stuffedMedium(
    id: '032',
    name: 'stuffed medium',
    category: ProductCategory.stuffed,
    description: 'stuffed! stuffed!',
    tag: 'stu_medium',
    price: 100000,
    imagePath: 'images/stuffed_medium.png',
  ),
  ;

  const Product({
    required this.id,
    required this.name,
    required this.category,
    required this.description,
    required this.tag,
    required this.price,
    required this.imagePath,
  });

  final String id;
  final String name;
  final ProductCategory category;
  final String description;
  final String tag;
  final int price;
  final String imagePath;

  static List<Product> get stuffed => [
        stuffedDash2,
        stuffedBig,
        stuffedGlasses,
        stuffedMedium,
      ];

  static List<Product> get tshirt => [
        tshirtDash,
        tshirtGlasses,
        tshirtHi,
        tshirtCombi,
        tshirtDarth,
        tshirtRocket,
        tshirtSing,
        tshirtShouting,
      ];

  static List<Product> get sticker => [
        stickerDash,
        stickerDartSide,
        stickerSinging,
        stickerShouting,
        stickerGlasses,
        stickerTeaching,
        stickerLove,
      ];

  static List<Product> get image => [
        bunny,
        coffee,
        fire,
        guiter,
        gym,
        pencil,
        professor,
        superman,
        artist,
        sleep,
        skateboard,
        donut,
      ];

  static List<Product> get all => [
        ...stuffed,
        ...tshirt,
        ...sticker,
        ...image,
      ];
}

enum ProductCategory {
  image,
  sticker,
  tshirt,
  stuffed;
}
